
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\037\000\002\002\005\000\002\002\004\000\002\002" +
    "\004\000\002\003\003\000\002\003\005\000\002\003\005" +
    "\000\002\003\005\000\002\003\004\000\002\003\005\000" +
    "\002\003\005\000\002\003\005\000\002\003\005\000\002" +
    "\003\005\000\002\003\003\000\002\003\003\000\002\003" +
    "\003\000\002\003\005\000\002\003\010\000\002\003\005" +
    "\000\002\003\005\000\002\003\005\000\002\003\005\000" +
    "\002\003\005\000\002\003\005\000\002\003\004\000\002" +
    "\003\005\000\002\003\005\000\002\003\012\000\002\003" +
    "\010\000\002\003\010\000\002\003\010" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\117\000\036\005\010\007\004\014\022\016\016\020" +
    "\021\022\014\023\013\024\012\025\023\026\015\040\017" +
    "\043\006\044\007\047\005\001\002\000\036\005\010\007" +
    "\004\014\022\016\016\020\021\022\014\023\013\024\012" +
    "\025\023\026\015\040\017\043\006\044\007\047\005\001" +
    "\002\000\004\014\114\001\002\000\004\042\112\001\002" +
    "\000\004\043\105\001\002\000\004\043\100\001\002\000" +
    "\040\002\075\005\010\007\004\014\022\016\016\020\021" +
    "\022\014\023\013\024\012\025\023\026\015\040\017\043" +
    "\006\044\007\047\005\001\002\000\050\004\ufff4\006\ufff4" +
    "\007\ufff4\010\ufff4\012\ufff4\013\ufff4\015\ufff4\017\ufff4\021" +
    "\ufff4\027\ufff4\030\ufff4\031\ufff4\032\ufff4\033\ufff4\034\ufff4" +
    "\035\ufff4\036\ufff4\037\ufff4\041\ufff4\001\002\000\050\004" +
    "\ufffe\006\ufffe\007\ufffe\010\ufffe\012\ufffe\013\ufffe\015\ufffe" +
    "\017\ufffe\021\ufffe\027\ufffe\030\ufffe\031\ufffe\032\ufffe\033" +
    "\ufffe\034\ufffe\035\ufffe\036\ufffe\037\ufffe\041\ufffe\001\002" +
    "\000\050\004\ufff2\006\ufff2\007\ufff2\010\ufff2\012\ufff2\013" +
    "\ufff2\015\ufff2\017\ufff2\021\ufff2\027\ufff2\030\ufff2\031\ufff2" +
    "\032\ufff2\033\ufff2\034\ufff2\035\ufff2\036\ufff2\037\ufff2\041" +
    "\ufff2\001\002\000\004\014\066\001\002\000\036\005\010" +
    "\007\004\014\022\016\016\020\021\022\014\023\013\024" +
    "\012\025\023\026\015\040\017\043\006\044\007\047\005" +
    "\001\002\000\036\005\010\007\004\014\022\016\016\020" +
    "\021\022\014\023\013\024\012\025\023\026\015\040\017" +
    "\043\006\044\007\047\005\001\002\000\036\004\062\006" +
    "\032\007\025\010\040\012\035\013\027\030\033\031\031" +
    "\032\041\033\036\034\034\035\030\036\026\037\042\001" +
    "\002\000\036\005\010\007\004\014\022\016\016\020\021" +
    "\022\014\023\013\024\012\025\023\026\015\040\017\043" +
    "\006\044\007\047\005\001\002\000\036\005\010\007\004" +
    "\014\022\016\016\020\021\022\014\023\013\024\012\025" +
    "\023\026\015\040\017\043\006\044\007\047\005\001\002" +
    "\000\050\004\ufff3\006\ufff3\007\ufff3\010\ufff3\012\ufff3\013" +
    "\ufff3\015\ufff3\017\ufff3\021\ufff3\027\ufff3\030\ufff3\031\ufff3" +
    "\032\ufff3\033\ufff3\034\ufff3\035\ufff3\036\ufff3\037\ufff3\041" +
    "\ufff3\001\002\000\036\006\032\007\025\010\040\012\035" +
    "\013\027\015\037\030\033\031\031\032\041\033\036\034" +
    "\034\035\030\036\026\037\042\001\002\000\036\005\010" +
    "\007\004\014\022\016\016\020\021\022\014\023\013\024" +
    "\012\025\023\026\015\040\017\043\006\044\007\047\005" +
    "\001\002\000\036\005\010\007\004\014\022\016\016\020" +
    "\021\022\014\023\013\024\012\025\023\026\015\040\017" +
    "\043\006\044\007\047\005\001\002\000\036\005\010\007" +
    "\004\014\022\016\016\020\021\022\014\023\013\024\012" +
    "\025\023\026\015\040\017\043\006\044\007\047\005\001" +
    "\002\000\036\005\010\007\004\014\022\016\016\020\021" +
    "\022\014\023\013\024\012\025\023\026\015\040\017\043" +
    "\006\044\007\047\005\001\002\000\036\005\010\007\004" +
    "\014\022\016\016\020\021\022\014\023\013\024\012\025" +
    "\023\026\015\040\017\043\006\044\007\047\005\001\002" +
    "\000\036\005\010\007\004\014\022\016\016\020\021\022" +
    "\014\023\013\024\012\025\023\026\015\040\017\043\006" +
    "\044\007\047\005\001\002\000\036\005\010\007\004\014" +
    "\022\016\016\020\021\022\014\023\013\024\012\025\023" +
    "\026\015\040\017\043\006\044\007\047\005\001\002\000" +
    "\036\005\010\007\004\014\022\016\016\020\021\022\014" +
    "\023\013\024\012\025\023\026\015\040\017\043\006\044" +
    "\007\047\005\001\002\000\036\005\010\007\004\014\022" +
    "\016\016\020\021\022\014\023\013\024\012\025\023\026" +
    "\015\040\017\043\006\044\007\047\005\001\002\000\036" +
    "\005\010\007\004\014\022\016\016\020\021\022\014\023" +
    "\013\024\012\025\023\026\015\040\017\043\006\044\007" +
    "\047\005\001\002\000\050\004\ufff7\006\ufff7\007\ufff7\010" +
    "\ufff7\012\ufff7\013\ufff7\015\ufff7\017\ufff7\021\ufff7\027\ufff7" +
    "\030\ufff7\031\ufff7\032\ufff7\033\ufff7\034\ufff7\035\ufff7\036" +
    "\ufff7\037\ufff7\041\ufff7\001\002\000\036\005\010\007\004" +
    "\014\022\016\016\020\021\022\014\023\013\024\012\025" +
    "\023\026\015\040\017\043\006\044\007\047\005\001\002" +
    "\000\036\005\010\007\004\014\022\016\016\020\021\022" +
    "\014\023\013\024\012\025\023\026\015\040\017\043\006" +
    "\044\007\047\005\001\002\000\036\005\010\007\004\014" +
    "\022\016\016\020\021\022\014\023\013\024\012\025\023" +
    "\026\015\040\017\043\006\044\007\047\005\001\002\000" +
    "\050\004\uffe7\006\uffe7\007\uffe7\010\uffe7\012\uffe7\013\uffe7" +
    "\015\uffe7\017\uffe7\021\uffe7\027\uffe7\030\033\031\031\032" +
    "\041\033\036\034\034\035\030\036\026\037\uffe7\041\uffe7" +
    "\001\002\000\050\004\uffef\006\uffef\007\uffef\010\uffef\012" +
    "\uffef\013\uffef\015\uffef\017\uffef\021\uffef\027\uffef\030\uffef" +
    "\031\uffef\032\uffef\033\uffef\034\uffef\035\uffef\036\uffef\037" +
    "\uffef\041\uffef\001\002\000\050\004\ufffb\006\ufffb\007\ufffb" +
    "\010\ufffb\012\035\013\027\015\ufffb\017\ufffb\021\ufffb\027" +
    "\ufffb\030\033\031\031\032\041\033\036\034\034\035\030" +
    "\036\026\037\042\041\ufffb\001\002\000\050\004\uffee\006" +
    "\uffee\007\uffee\010\uffee\012\uffee\013\uffee\015\uffee\017\uffee" +
    "\021\uffee\027\uffee\030\uffee\031\uffee\032\uffee\033\uffee\034" +
    "\uffee\035\uffee\036\uffee\037\uffee\041\uffee\001\002\000\050" +
    "\004\ufff9\006\ufff9\007\ufff9\010\ufff9\012\ufff9\013\027\015" +
    "\ufff9\017\ufff9\021\ufff9\027\ufff9\030\033\031\031\032\041" +
    "\033\036\034\034\035\030\036\026\037\042\041\ufff9\001" +
    "\002\000\050\004\uffed\006\uffed\007\uffed\010\uffed\012\uffed" +
    "\013\uffed\015\uffed\017\uffed\021\uffed\027\uffed\030\uffed\031" +
    "\uffed\032\uffed\033\uffed\034\uffed\035\uffed\036\uffed\037\uffed" +
    "\041\uffed\001\002\000\050\004\uffeb\006\uffeb\007\uffeb\010" +
    "\uffeb\012\uffeb\013\uffeb\015\uffeb\017\uffeb\021\uffeb\027\uffeb" +
    "\030\uffeb\031\uffeb\032\041\033\036\034\034\035\030\036" +
    "\uffeb\037\uffeb\041\uffeb\001\002\000\050\004\ufffd\006\ufffd" +
    "\007\ufffd\010\040\012\035\013\027\015\ufffd\017\ufffd\021" +
    "\ufffd\027\ufffd\030\033\031\031\032\041\033\036\034\034" +
    "\035\030\036\026\037\042\041\ufffd\001\002\000\050\004" +
    "\uffea\006\uffea\007\uffea\010\uffea\012\uffea\013\uffea\015\uffea" +
    "\017\uffea\021\uffea\027\uffea\030\uffea\031\uffea\032\041\033" +
    "\036\034\034\035\030\036\uffea\037\uffea\041\uffea\001\002" +
    "\000\050\004\uffec\006\uffec\007\uffec\010\uffec\012\uffec\013" +
    "\uffec\015\uffec\017\uffec\021\uffec\027\uffec\030\uffec\031\uffec" +
    "\032\uffec\033\uffec\034\uffec\035\uffec\036\uffec\037\uffec\041" +
    "\uffec\001\002\000\050\004\ufff8\006\ufff8\007\ufff8\010\ufff8" +
    "\012\035\013\027\015\ufff8\017\ufff8\021\ufff8\027\ufff8\030" +
    "\033\031\031\032\041\033\036\034\034\035\030\036\026" +
    "\037\042\041\ufff8\001\002\000\050\004\uffe8\006\uffe8\007" +
    "\uffe8\010\uffe8\012\uffe8\013\uffe8\015\uffe8\017\uffe8\021\uffe8" +
    "\027\uffe8\030\033\031\031\032\041\033\036\034\034\035" +
    "\030\036\uffe8\037\uffe8\041\uffe8\001\002\000\050\004\ufffc" +
    "\006\ufffc\007\ufffc\010\040\012\035\013\027\015\ufffc\017" +
    "\ufffc\021\ufffc\027\ufffc\030\033\031\031\032\041\033\036" +
    "\034\034\035\030\036\026\037\042\041\ufffc\001\002\000" +
    "\036\006\032\007\025\010\040\012\035\013\027\021\061" +
    "\030\033\031\031\032\041\033\036\034\034\035\030\036" +
    "\026\037\042\001\002\000\050\004\ufff6\006\ufff6\007\ufff6" +
    "\010\ufff6\012\ufff6\013\ufff6\015\ufff6\017\ufff6\021\ufff6\027" +
    "\ufff6\030\ufff6\031\ufff6\032\ufff6\033\ufff6\034\ufff6\035\ufff6" +
    "\036\ufff6\037\ufff6\041\ufff6\001\002\000\040\002\uffff\005" +
    "\uffff\007\uffff\014\uffff\016\uffff\020\uffff\022\uffff\023\uffff" +
    "\024\uffff\025\uffff\026\uffff\040\uffff\043\uffff\044\uffff\047" +
    "\uffff\001\002\000\050\004\uffe9\006\uffe9\007\uffe9\010\uffe9" +
    "\012\uffe9\013\uffe9\015\uffe9\017\uffe9\021\uffe9\027\uffe9\030" +
    "\033\031\031\032\041\033\036\034\034\035\030\036\uffe9" +
    "\037\uffe9\041\uffe9\001\002\000\036\006\032\007\025\010" +
    "\040\012\035\013\027\017\065\030\033\031\031\032\041" +
    "\033\036\034\034\035\030\036\026\037\042\001\002\000" +
    "\050\004\ufff5\006\ufff5\007\ufff5\010\ufff5\012\ufff5\013\ufff5" +
    "\015\ufff5\017\ufff5\021\ufff5\027\ufff5\030\ufff5\031\ufff5\032" +
    "\ufff5\033\ufff5\034\ufff5\035\ufff5\036\ufff5\037\ufff5\041\ufff5" +
    "\001\002\000\036\005\010\007\004\014\022\016\016\020" +
    "\021\022\014\023\013\024\012\025\023\026\015\040\017" +
    "\043\006\044\007\047\005\001\002\000\036\006\032\007" +
    "\025\010\040\012\035\013\027\015\070\030\033\031\031" +
    "\032\041\033\036\034\034\035\030\036\026\037\042\001" +
    "\002\000\004\041\071\001\002\000\036\005\010\007\004" +
    "\014\022\016\016\020\021\022\014\023\013\024\012\025" +
    "\023\026\015\040\017\043\006\044\007\047\005\001\002" +
    "\000\050\004\uffe5\006\032\007\025\010\040\012\035\013" +
    "\027\015\uffe5\017\uffe5\021\uffe5\027\073\030\033\031\031" +
    "\032\041\033\036\034\034\035\030\036\026\037\042\041" +
    "\uffe5\001\002\000\036\005\010\007\004\014\022\016\016" +
    "\020\021\022\014\023\013\024\012\025\023\026\015\040" +
    "\017\043\006\044\007\047\005\001\002\000\050\004\uffe6" +
    "\006\uffe6\007\uffe6\010\uffe6\012\uffe6\013\uffe6\015\uffe6\017" +
    "\uffe6\021\uffe6\027\uffe6\030\uffe6\031\uffe6\032\uffe6\033\uffe6" +
    "\034\uffe6\035\uffe6\036\uffe6\037\uffe6\041\uffe6\001\002\000" +
    "\004\002\000\001\002\000\036\004\077\006\032\007\025" +
    "\010\040\012\035\013\027\030\033\031\031\032\041\033" +
    "\036\034\034\035\030\036\026\037\042\001\002\000\040" +
    "\002\001\005\001\007\001\014\001\016\001\020\001\022" +
    "\001\023\001\024\001\025\001\026\001\040\001\043\001" +
    "\044\001\047\001\001\002\000\004\046\101\001\002\000" +
    "\004\045\102\001\002\000\036\005\010\007\004\014\022" +
    "\016\016\020\021\022\014\023\013\024\012\025\023\026" +
    "\015\040\017\043\006\044\007\047\005\001\002\000\036" +
    "\006\032\007\025\010\040\012\035\013\027\030\033\031" +
    "\031\032\041\033\036\034\034\035\030\036\026\037\042" +
    "\041\104\001\002\000\050\004\uffe4\006\uffe4\007\uffe4\010" +
    "\uffe4\012\uffe4\013\uffe4\015\uffe4\017\uffe4\021\uffe4\027\uffe4" +
    "\030\uffe4\031\uffe4\032\uffe4\033\uffe4\034\uffe4\035\uffe4\036" +
    "\uffe4\037\uffe4\041\uffe4\001\002\000\004\014\106\001\002" +
    "\000\004\015\107\001\002\000\004\041\110\001\002\000" +
    "\036\005\010\007\004\014\022\016\016\020\021\022\014" +
    "\023\013\024\012\025\023\026\015\040\017\043\006\044" +
    "\007\047\005\001\002\000\050\004\ufff0\006\032\007\025" +
    "\010\040\012\035\013\027\015\ufff0\017\ufff0\021\ufff0\027" +
    "\ufff0\030\033\031\031\032\041\033\036\034\034\035\030" +
    "\036\026\037\042\041\ufff0\001\002\000\036\005\010\007" +
    "\004\014\022\016\016\020\021\022\014\023\013\024\012" +
    "\025\023\026\015\040\017\043\006\044\007\047\005\001" +
    "\002\000\050\004\ufff1\006\032\007\025\010\040\012\035" +
    "\013\027\015\ufff1\017\ufff1\021\ufff1\027\ufff1\030\033\031" +
    "\031\032\041\033\036\034\034\035\030\036\026\037\042" +
    "\041\ufff1\001\002\000\036\005\010\007\004\014\022\016" +
    "\016\020\021\022\014\023\013\024\012\025\023\026\015" +
    "\040\017\043\006\044\007\047\005\001\002\000\036\006" +
    "\032\007\025\010\040\012\035\013\027\015\116\030\033" +
    "\031\031\032\041\033\036\034\034\035\030\036\026\037" +
    "\042\001\002\000\004\041\117\001\002\000\036\005\010" +
    "\007\004\014\022\016\016\020\021\022\014\023\013\024" +
    "\012\025\023\026\015\040\017\043\006\044\007\047\005" +
    "\001\002\000\050\004\uffe3\006\032\007\025\010\040\012" +
    "\035\013\027\015\uffe3\017\uffe3\021\uffe3\027\uffe3\030\033" +
    "\031\031\032\041\033\036\034\034\035\030\036\026\037" +
    "\042\041\uffe3\001\002\000\050\004\ufffa\006\ufffa\007\ufffa" +
    "\010\040\012\035\013\027\015\ufffa\017\ufffa\021\ufffa\027" +
    "\ufffa\030\033\031\031\032\041\033\036\034\034\035\030" +
    "\036\026\037\042\041\ufffa\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\117\000\006\002\010\003\017\001\001\000\004\003" +
    "\120\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\003\075\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\003\063\001\001\000\004\003\062\001" +
    "\001\000\002\001\001\000\004\003\057\001\001\000\004" +
    "\003\023\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\003\056\001\001\000\004\003\055\001\001\000\004" +
    "\003\054\001\001\000\004\003\053\001\001\000\004\003" +
    "\052\001\001\000\004\003\051\001\001\000\004\003\050" +
    "\001\001\000\004\003\047\001\001\000\004\003\046\001" +
    "\001\000\004\003\045\001\001\000\002\001\001\000\004" +
    "\003\044\001\001\000\004\003\043\001\001\000\004\003" +
    "\042\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\003\066\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\003\071\001\001\000\002\001\001\000" +
    "\004\003\073\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\003\102\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\003\110\001\001\000\002\001\001" +
    "\000\004\003\112\001\001\000\002\001\001\000\004\003" +
    "\114\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\003\117\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return s.next_token(); 
    }


    scanner s;
    parser(scanner s){ this.s=s; }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // expr_list ::= expr_list expr SEMI 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 System.out.println(e);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= expr_list EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expr_list ::= expr SEMI 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 System.out.println(e);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expr ::= LETRA 
            {
              Object RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = l; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // expr ::= expr PLUS expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = (Integer)e1+(Integer)e2;       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expr ::= expr MINUS expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = (Integer)e1-(Integer)e2;       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expr ::= expr TIMES expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = (Integer)e1*(Integer)e2;       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expr ::= MINUS expr 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = -(Integer)e;          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expr ::= expr DIV expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = (Integer)e1/(Integer)e2;       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expr ::= expr MOD expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = (Integer)e1%(Integer)e2;       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // expr ::= LPAREN expr RPAREN 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e;           
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // expr ::= LBRACKET expr RBRACKET 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e;           
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // expr ::= CLBRACKET expr CRBRACKET 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e;           
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // expr ::= NUMBER 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n;           
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // expr ::= FLOAT 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Float f = (Float)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f.floatValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expr ::= STRING 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expr ::= IDENT AT expr 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e;           
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expr ::= FUNC IDENT LPAREN RPAREN DELIMITER expr 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e;           
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expr ::= expr LT expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = ((Number)e1).doubleValue() < ((Number)e2).doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expr ::= expr GT expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = ((Number)e1).doubleValue() > ((Number)e2).doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expr ::= expr LE expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = ((Number)e1).doubleValue() <= ((Number)e2).doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expr ::= expr GE expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = ((Number)e1).doubleValue() >= ((Number)e2).doubleValue(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expr ::= expr EQ expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e1.equals(e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expr ::= expr NEQ expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = !e1.equals(e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expr ::= NOT expr 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = !((Boolean)e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expr ::= expr AND expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = ((Boolean)e1) && ((Boolean)e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr ::= expr OR expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = ((Boolean)e1) || ((Boolean)e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expr ::= IF LPAREN expr RPAREN DELIMITER expr ELSE expr 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int then_exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int then_exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object then_expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int else_exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int else_exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object else_expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
           Boolean cond = (Boolean) e;
           RESULT = cond ? then_expr : else_expr;
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr ::= IF LPAREN expr RPAREN DELIMITER expr 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int then_exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int then_exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object then_expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
           Boolean cond = (Boolean) e;
           RESULT = cond ? then_expr : null;
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expr ::= FOR IDENT IN RANGE expr DELIMITER 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        int limite = ((Number)e).intValue();
        for (int i = 1; i <= limite; i++) {
            System.out.println(i);
        }
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expr ::= WHILE LPAREN expr RPAREN DELIMITER expr 
            {
              Object RESULT =null;
		int condleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object cond = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        while (true) {
            Boolean c = (Boolean)cond;

            if (!c)
                break;
            System.out.println(body);
            break;
        }

        RESULT = null;
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
