
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DELIMITER = 31;
  public static final int LBRACKET = 14;
  public static final int CRBRACKET = 13;
  public static final int GE = 27;
  public static final int UMINUS = 7;
  public static final int LPAREN = 10;
  public static final int SEMI = 2;
  public static final int FOR = 3;
  public static final int MINUS = 5;
  public static final int RPAREN = 11;
  public static final int NOT = 30;
  public static final int AND = 28;
  public static final int RANGE = 35;
  public static final int LT = 24;
  public static final int IN = 36;
  public static final int LETRA = 17;
  public static final int OR = 29;
  public static final int DIV = 8;
  public static final int PLUS = 4;
  public static final int IF = 20;
  public static final int LE = 26;
  public static final int EOF = 0;
  public static final int RBRACKET = 15;
  public static final int error = 1;
  public static final int NUMBER = 18;
  public static final int MOD = 9;
  public static final int NEQ = 23;
  public static final int CLBRACKET = 12;
  public static final int IDENT = 33;
  public static final int EQ = 22;
  public static final int TIMES = 6;
  public static final int ELSE = 21;
  public static final int FUNC = 34;
  public static final int WHILE = 37;
  public static final int FLOAT = 19;
  public static final int STRING = 16;
  public static final int AT = 32;
  public static final int GT = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "FOR",
  "PLUS",
  "MINUS",
  "TIMES",
  "UMINUS",
  "DIV",
  "MOD",
  "LPAREN",
  "RPAREN",
  "CLBRACKET",
  "CRBRACKET",
  "LBRACKET",
  "RBRACKET",
  "STRING",
  "LETRA",
  "NUMBER",
  "FLOAT",
  "IF",
  "ELSE",
  "EQ",
  "NEQ",
  "LT",
  "GT",
  "LE",
  "GE",
  "AND",
  "OR",
  "NOT",
  "DELIMITER",
  "AT",
  "IDENT",
  "FUNC",
  "RANGE",
  "IN",
  "WHILE"
  };
}

